source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug "icantjuddle/ayu-kak" theme config %{
	colorscheme ayu-dark
	face global BufferPadding default,default # get rid of gaudy light background on short files
}

plug "kak-lsp/kak-lsp" do %{
	cargo install --locked --force --path .
} config %{
	map -docstring 'lsp hover' global normal '<c-k>' ':lsp-hover<ret>'
}

plug "lePerdu/kakboard" %{
    hook global WinCreate .* %{ kakboard-enable }
}

plug "andreyorst/fzf.kak" config %{
	map -docstring 'fzf mode' global normal '<c-t>' ': fzf-mode<ret>'
} defer "fzf" %{
	set-option global fzf_preview_width '65%'
	set-option global fzf_project_use_tilda true
	evaluate-commands %sh{
		if [ -n "$(command -v fd)" ]; then
			echo "set-option global fzf_file_command %{fd . --no-ignore --type f --follow --hidden --exclude .git --exclude .svn}"
		else
			echo "set-option global fzf_file_command %{find . \( -path '*/.svn*' -o -path '*/.git*' \) -prune -o -type f -follow -print}"
		fi
		[ -n "$(command -v bat)" ] && echo "set-option global fzf_highlight_command bat"
		[ -n "${kak_opt_grepcmd}" ] && echo "set-option global fzf_sk_grep_command %{${kak_opt_grepcmd}}"
	}
}

map -docstring 'buffer back' global normal '<c-p>' ':buffer-previous<ret>'
map -docstring 'buffer next' global normal '<c-n>' ':buffer-next<ret>'
