#!/bin/bash

# iv597's HSWM config. Derived from the default.

function hc() {
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

hc detect_monitors

# keybindings
Mod=Mod4
hc keybind $Mod-Shift-r reload

hc keybind $Mod-Home spawn xautolock -locknow
hc keybind $Mod-End close

hc keybind $Mod-Shift-Return spawn termite
hc keybind $Mod-space spawn dmenu_run -fn "Fira Mono-8" -q -h 15 -nb "#151515" -nf "#d0d0d0" -sb "#151515" -sf "#688c7d" -p "run »"

hc keybind $Mod-F12 spawn amixer -c 1 set Master playback 1%+
hc keybind XF86AudioRaiseVolume spawn amixer -c 1 set Master playback 1%+
hc keybind $Mod-F11 spawn amixer -c 1 set Master playback 1%-
hc keybind XF86AudioLowerVolume spawn amixer -c 1 set Master playback 1%-
hc keybind $Mod-F10 spawn amixer -c 1 set Master toggle
hc keybind XF86AudioMute spawn amixer -c 1 set Master toggle

hc keybind $Mod-F2 spawn xbacklight -inc 3
hc keybind $Mod-F1 spawn xbacklight -dec 3
hc keybind XF86MonBrightnessUp spawn xbacklight -inc 3
hc keybind XF86MonBrightnessDown spawn xbacklight -dec 3

#hc keybind $Mod-0xffc1 spawn /home/j/bin/touchpad_toggle.sh

# tags
TAG_NAMES=( {1..9} )
TAG_KEYS=( {1..9} 0 )

hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
    hc add "${TAG_NAMES[$i]}"
    key="${TAG_KEYS[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use "${TAG_NAMES[$i]}"
        hc keybind "$Mod-Shift-$key" move "${TAG_NAMES[$i]}"
    fi
done

# layouting
hc keybind $Mod-Control-r remove
hc keybind $Mod-Control-space cycle_layout 1

hc keybind $Mod-a split horizontal 0.33
hc keybind $Mod-o split vertical 0.33
hc keybind $Mod-e split horizontal 0.5
hc keybind $Mod-u split vertical 0.5

hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# resizing
RESIZESTEP=0.05
hc keybind $Mod-Control-h resize left +$RESIZESTEP
hc keybind $Mod-Control-j resize down +$RESIZESTEP
hc keybind $Mod-Control-k resize up +$RESIZESTEP
hc keybind $Mod-Control-l resize right +$RESIZESTEP

# focus
hc keybind $Mod-Tab cycle_monitor
hc keybind $Mod-Shift-Tab cycle_all +1
hc keybind $Mod-c cycle
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

# colors
hc set frame_bg_transparent 2
hc set frame_border_width 0
hc set window_border_width 4
hc set window_border_normal_color '#111111'
hc set window_border_active_color '#5e5e5e'

# spacing
hc set frame_gap -30
hc set window_gap 30

# rules
hc unrule -F
hc rule focus=off # normally do not focus new clients
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off

# make room for conky
# pad MONITOR [PADUP [PADRIGHT [PADDOWN [PADLEFT]]]]
hc pad 0 32 32 32 32
hc pad 1 32 32 32 32
hc pad 2 32 32 32 32

